version: "3.7"

services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    container_name: productdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: marketplaceProduct
      MYSQL_USER: adminproduct
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: Amila_Rpw
    volumes:
      - mysql-data-product:/var/lib/mysql

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  mysql-data-product:
